### ISSUE TITLE
Notebook fails on model register phase

### ISSUE THREAD

**Issue by mapat1994** [Azure/aml-real-time-ai#28]
When running step 0 of 00_QuickStart notebook ran into this error:

Creating storage account fpga7ae4fcb810a4c6b6cfdb

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-789f253437a6> in <module>()
----> 1 model_id = deployment_client.register_model(model_name, service_def_path)

e:\work\aml-real-time-ai\pythonlib\amlrealtimeai\deployment_client.py in register_model(self, model_name, service_def)
     45 
     46     def register_model(self, model_name, service_def):
---> 47         storage_account_key = self.__create_storage_account_and_get_key()
     48         cloud_storage_account = CloudStorageAccount(self.__storage_account_name, storage_account_key)
     49 

e:\work\aml-real-time-ai\pythonlib\amlrealtimeai\deployment_client.py in __create_storage_account_and_get_key(self)
    277                 self.__storage_account_name,
    278                 StorageAccountCreateParameters(
--> 279                     sku=Sku(SkuName.standard_ragrs),
    280                     kind=Kind.storage,
    281                     location=self.__location

TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by wtam** [comment]
I still received the same error thought I;m already using @csteegz  latest update that specified the specific dependency
 'tensorflow==1.6.0', 'keras==2.1.5', 'requests==2.18.4', 'adal==1.0.2', 'azure-storage', 'azure.mgmt.storage==1.5.0'

**Comment by csteegz** [comment]
Can you check the packages that you have installed? If you have a later version of azure-storage installed I don't think it would get downgraded when you install a new package. Might also help to install this in a virtualenv.

**Comment by wtam** [comment]
Thanks @csteegz, I removed all my conda env and re-install azure-mgmt-storage and now is working:)

below is my current azure-storage in my conda env 
azure-mgmt-storage        1.5.0                     <pip>
azure-storage             0.36.0                    <pip>
